### ISSUE TITLE
app.py seems to be missing

### ISSUE THREAD

**Issue by JustaWalrus** [fabiogra/moseca#3]
I could just be missing something, but I can't currently do much in the webUI due to it relying on a module called "app" which doesn't seem to exist. any help would be appreciated.

**Comment by fabiogra** [comment]
You need to set the PYTHONPATH to the root of the folder. Thanks for the feedback, I've added to the README.

**Comment by JustaWalrus** [comment]
Cheers, that seems to have worked. However, a couple of problems I've noticed, is A: the fast vocal seperator option requires a file called "baseline.pth" which the app can't find. and B: that the download feature from the audio preview gets blocked by other interface elements. The files can still be fished out of tmp/htdemucs/FILENAME_HERE though, so it's no dealbreaker.

**Comment by fabiogra** [comment]
You are right, I have to add also a comment to download the model `baseline.pth` from https://huggingface.co/fabiogra/baseline_vocal_remover

Regarding B, I didn't get it... Can you explain to me in detail the issue and how to replicate it? If you can show a screenshot would be great!

**Comment by JustaWalrus** [comment]
![Screenshot from 2023-07-14 15-42-38](https://github.com/fabiogra/moseca/assets/103149004/bb4dba2c-d19d-48dd-8a24-8abf2b57ddae)
In the screenshot provided above, the song playback ui element's download option that should appear above "Playback speed" gets cut off. weirdly enough, the container itself adjusts perfectly when changing it's width, but it's height seems set in stone.

**Comment by fabiogra** [comment]
Thanks, now I see. This is because that player is using an external library "streamlit_player" with height reduced to maintain a similar style of the original st.audio player. 

I should replace streamlit_player with st.audio where don't need to listen to events, so everywhere except for the karaoke.

**Comment by fabiogra** [comment]
I've updated the readme and the app with the st.audio player, you should not see any more that cut above playback speed

**Comment by JustaWalrus** [comment]
Thank you for the swift fixes and the very professional webUI. I'll go ahead and close the issue now
