### ISSUE TITLE
Docker installation fails

### ISSUE THREAD

**Issue by nekiee13** [fabiogra/moseca#7]
Original code failed. 

Tried to add a yt-dlp at line 8. No change
apt-get install -y ffmpeg jq curl yt-dlp && \

Tried to copy scripts - no change
COPY scripts/prepare_samples.sh /prepare_samples.sh
COPY scripts/inference.py /inference.py

Tried modify executable
RUN chmod +x prepare_samples.sh
RUN ls -l /
RUN sh -x ./prepare_samples.sh

This is error description I get all the time:

 => ERROR [stage-0 15/16] RUN sh -x ./prepare_samples.sh                                                           0.5s
------
 > [stage-0 15/16] RUN sh -x ./prepare_samples.sh:
#0 0.504 + echo Starting prepare_samples.sh...
#0 0.504 Starting prepare_samples.sh...
#0 0.504 + cat /run/secrets/PREPARE_SAMPLES
#0 0.505 cat: /run/secrets/PREPARE_SAMPLES: No such file or directory
#0 0.505 + export PREPARE_SAMPLES=
#0 0.505 +
: not foundprepare_samples.sh: 5:
#0 0.505 ./prepare_samples.sh: 18: Syntax error: word unexpected (expecting "do")
------
Dockerfile:36
--------------------
  34 |     RUN chmod +x prepare_samples.sh
  35 |     RUN ls -l /
  36 | >>> RUN sh -x ./prepare_samples.sh
  37 |
  38 |
--------------------
ERROR: failed to solve: process "/bin/sh -c sh -x ./prepare_samples.sh" did not complete successfully: exit code: 2

**Comment by fabiogra** [comment]
Hey @nekiee13, did you pull the repo in Windows OS?

**Comment by nekiee13** [comment]
Hi,
i git cloned repo.

**Comment by nekiee13** [comment]
I work under win11. Got docker installed, nVidia 4070 drivers and nvcc
active I know that nVidia got to be separatly added to docke (dont know how
to do it), cpp Toolkit, ms desktop Toolkit,  cpp compiler  and debugger
also separately. I really  think a got everything covered, but I'm not
programmer and just can't get it to work. I don't understand why script
don't see script, cause they are there. I tried to copy them in main
directory, but didn't succeed. When thinking now, maybe I should have  used
.\ instead of ./... will try that, but I don't know..

**Comment by fabiogra** [comment]
If you cloned the repo on a Windows machine, it might have converted the line endings in the shell script files. You could try to convert them back to UNIX format by running dos2unix prepare_samples.sh

You could also try to add this line in the Dockerfile (before RUN chmod +x /prepare_samples.sh):

`RUN dos2unix /prepare_samples.sh`

Let me know if that worked :)

**Comment by nekiee13** [comment]
Ok, will try that. I'm on the road so, some time next week.... thank you
for helping me.

**Comment by kevinlinxc** [comment]
I had a different issue where the .sh file was not found, but dos2unix also solved it, just thought I'd post about it here:
![image](https://github.com/fabiogra/moseca/assets/44324811/d33a95e8-a781-4518-b804-22b792c08714)


Maybe make a note to run that command on Windows?
